import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'nivi',
      email: 'nivi@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'nikk',
      email: 'nikk@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Craft1',
      slug: 'craft11',
      category: 'craft',
      image: '/images/craft1.jpg',
      price: 70,
      brand: 'navneet',
      rating: 4.5,
      numReviews: 8,
      countinStock: 20,
      dscription: 'A popular craft1',
    },
    {
      name: 'Craft2',
      slug: 'craft12',
      category: 'craft',
      image: '/images/craft2.jpg',
      price: 80,
      brand: 'classmates',
      rating: 3.5,
      numReviews: 10,
      countinStock: 20,
      dscription: 'A popular craft2',
    },
    {
      name: 'Craft3',
      slug: 'craft13',
      category: 'craft',
      image: '/images/craft3.jpg',
      price: 50,
      brand: 'navneet',
      rating: 6.5,
      numReviews: 50,
      countinStock: 80,
      dscription: 'A popular craft3',
    },
    {
      name: 'Craft4',
      slug: 'craft14',
      category: 'craft',
      image: '/images/craft4.jpg',
      price: 50,
      brand: 'classmates',
      rating: 5.5,
      numReviews: 90,
      countinStock: 50,
      dscription: 'A popular craft4',
    },
    {
      name: 'Craft5',
      slug: 'craft15',
      category: 'craft',
      image: '/images/craft5.jpg',
      price: 40,
      brand: 'navneet',
      rating: 5.5,
      numReviews: 190,
      countinStock: 40,
      dscription: 'A popular Craft5',
    },
  ],
};
export default data;
